# Generated by Django 3.1 on 2020-09-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20200917_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='resign_reason',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='resign_type',
        ),
        migrations.CreateModel(
            name='Resign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resign_date', models.DateField()),
                ('resign_type', models.CharField(max_length=50)),
                ('resign_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.employee')),
            ],
        ),
    ]
