# Generated by Django 3.1 on 2020-08-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20200831_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leave_request',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
