# Generated by Django 3.1 on 2020-08-31 08:56

from django.db import migrations
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20200831_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='end_date',
            field=leave.models.CustomDateTimeField(),
        ),
        migrations.AlterField(
            model_name='leave_request',
            name='start_date',
            field=leave.models.CustomDateTimeField(),
        ),
    ]
