# Generated by Django 3.1 on 2020-08-31 10:20

from django.db import migrations
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_auto_20200831_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='end_date',
            field=leave.models.CustomDateTimeField(),
        ),
        migrations.AlterField(
            model_name='leave_request',
            name='start_date',
            field=leave.models.CustomDateTimeField(),
        ),
    ]
