# Generated by Django 3.1 on 2020-08-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_auto_20200831_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
