export const URL = "http://192.168.8.250:1111/";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";

export const GET_LEAVE_TYPES = "GET_LEAVE_TYPES";
export const ADD_LEAVE_TYPE = "ADD_LEAVE_TYPE";
export const DELETE_LEAVE_TYPE = "DELETE_LEAVE_TYPE";
export const UPDATE_LEAVE_TYPE = "UPDATE_LEAVE_TYPE";

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";

export const GET_LEAVE_REQUESTS = "GET_LEAVE_REQUESTS";
export const ADD_LEAVE_REQUEST = "ADD_LEAVE_REQUEST";
export const DELETE_LEAVE_REQUEST = "DELETE_LEAVE_REQUEST";
export const UPDATE_LEAVE_REQUEST = "UPDATE_LEAVE_REQUEST";

export const GET_LEAVE_REQUEST_FILTER = "GET_LEAVE_REQUEST_FILTER";
export const GET_LEAVE_REQUEST_FILTER_NOTIF = "GET_LEAVE_REQUEST_FILTER_NOTIF";
